### ISSUE TITLE
Module not found: Error: Cannot resolve module 'babel-loader'

### ISSUE THREAD

**Issue by diamont1001** [diamont1001/webpack-summary#1]
有时候我们做项目的时候，会把一些公共代码放在项目目录的外面，比如：

libs目录：/home/web/libs
A项目目录：/home/web/project/a
B项目目录：/home/web/project/b

这样，想要在A项目里引用libs目录里的库的话，会报错 
`Module not found: Error: Cannot resolve module 'babel-loader'`

**Comment by atian25** [comment]
https://webpack.github.io/docs/resolving.html

**Comment by diamont1001** [comment]
## 找到原因了

A项目 `/home/web/project/a/index.js` 引用了 `/home/web/libs/lib1.js` 这样本来是没问题的

但是如果 `/home/web/libs/lib1.js` 再引用 `/home/web/libs/lib2.js` 就会出问题了，问题也是出现在这里

参考: [https://webpack.github.io/docs/resolving.html#loaders](https://webpack.github.io/docs/resolving.html#loaders)

> For resolving a module we first gather all search directories for modules from the context directory.

`/home/web/libs/` 目录已经不在webpack运行的context directory上了。

## 解决办法
- 自己修改babel-loader逻辑（原谅我很懒==||）

> 根据 @atian25 建议不这样做，公共代码尽量把它放到npm上去。

## 期待

期待其他大神提供更好的解决方案，issue就暂时不close了

**Comment by stxwd46** [comment]
1. webpack.config.js 是配置在/home/web/project 目录下的
2. /home/web/libs/lib1.js 是在 /home/web/project/a/index.js 里 require 的， 此时的上下文环境是在 project 目录下的，所以 babel-loader 可以对 lib1.js 生效
3. 但 /home/web/libs/lib2.js 是在 /home/web/libs/lib1.js 里 require 的，此时的上下文环境是在 libs 目录下的，所以 babel-loader 对 lib2.js 不生效
